trigger:
- master

strategy:
  matrix:
    Node6:
      nodejs_version: "6"
    NodeAny:
      nodejs_version: ""

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(nodejs_version)

- powershell: |
    npm config set spin false
    if ($env:nodejs_version -eq "6.9.5") {
      npm install -g npm@5
      [Environment]::SetEnvironmentVariable("NODE_LTS", "true", "User")
    } else {
      npm install -g npm@5
    }
    RefreshEnv
    npm install
  displayName: Install

- script: |
    node --version
    npm --version
    npm run test:both
  displayName: Test
